version: 2
jobs:
   build-job:
     docker:
       - image: circleci/ruby:latest
     steps:
       - checkout
       - run: bundle exec jekyll build
       - run: bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external
       - run: echo "hello world"
   deploy-job:
     docker:
       - image: circleci/ruby:latest
     steps:
       - run:
           command:
             - rsync -va --delete ./_site username@my-website:/var/html
