version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build
      - run: echo "Build finished!"
