version: 2
jobs:
   build-job:
     docker:
       - image: circleci/ruby:latest
     steps:
       - checkout
       - run: bundle install
       - run: bundle exec jekyll build
       - run: echo "hello world"
   deploy-job:
     docker:
       - image: circleci/ruby:latest
     steps:
       - run:
           command:
             - rsync -va --delete ./_site username@my-website:/var/html
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
